name: HH Vacancy Parser

on:
  repository_dispatch:
    types: [trigger-parser]
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run-parser:
    runs-on: ubuntu-latest

    # Даем серверу официальное право записывать файлы обратно в репозиторий
    permissions:
      contents: write

    steps:
    - name: Проверка кода репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests playwright

    - name: Install Playwright Browsers
      run: playwright install chromium

    - name: Запуск парсера вакансий
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_USER_ID: ${{ secrets.VK_USER_ID }}
      run: python parser.py

    - name: Автоматическое сохранение базы данных вакансий на GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add seen_vacancies.txt
        # Коммитим файл только если внутри появились новые записи, чтобы избежать пустых ошибок
        git diff --quiet && git diff --staged --quiet || (git commit -m "Автообновление базы вакансий: seen_vacancies.txt" && git push)
