name: HH Vacancy Parser

on:
  repository_dispatch:
    types: [trigger-parser]
  workflow_dispatch:
  schedule:
    # Запуск каждые 3 часа по всемирному времени UTC (в 03:00, 06:00, 09:00 и т.д.)
    - cron: '0 */3 * * *'

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests playwright

    - name: Install Playwright Browsers
      run: playwright install chromium

    - name: Запуск парсера вакансий
      # Прокидываем все скрытые переменные безопасности внутрь Ubuntu-контейнера
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
        VK_USER_ID: ${{ secrets.VK_USER_ID }}
      run: python parser.py

    - name: Сохранение базы данных вакансий
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: seen-vacancies-db
        path: seen_vacancies.txt
        retention-days: 90
